allowBuilds:
  '@sentry/cli': true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: false
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
overrides:
  '@esbuild-kit/core-utils>esbuild': ^0.28.1
  '@sentry/nextjs': 10.57.0
  '@sentry/types': 10.57.0
  'drizzle-kit>esbuild': ^0.28.1
  'monaco-editor>dompurify': ^3.4.0
  'next>postcss': ^8.5.15
  'terser-webpack-plugin>esbuild': ^0.28.1
peerDependencyRules:
  allowedVersions:
    next: 16.2.9
    sharp: 0.35.1
patchedDependencies:
  '@payload-bites/fullscreen-editor@1.7.2': patches/@payload-bites__fullscreen-editor@1.7.2.patch
  '@payload-bites/image-search@3.4.2': patches/@payload-bites__image-search@3.4.2.patch
minimumReleaseAgeExclude:
  - '@seshuk/payload-plugin-media-preview@1.1.1'
