export const managementOptions = [
  "Gerência Regional de Operações",
  "Gerência de Transporte e Logística",
  "Gerência de Serviços Compartilhados",
  "Gerência de Gente",
  "Gerência de Medicao e Faturamento",
  "Gerência de Frota",
  "Gerência de Facilities",
  "Gerência de Segurança e Sustentabilidade",
  "Gerência de Contabilidade e Finanças",
  "Gerência de Comunicação e Marketing",
] as const;

export type ManagementOption = (typeof managementOptions)[number];

export const jobTitleCatalog = [
  { code: 1, title: "Auxiliar Administrativo" },
  { code: 2, title: "Auxiliar de Eletricista" },
  { code: 3, title: "Supervisor e Contador de Qualidade" },
  { code: 5, title: "Supervisor de Equipe" },
  { code: 7, title: "Servente" },
  { code: 8, title: "Secretária Administrativa" },
  { code: 9, title: "Motorista de Caminhão Munck" },
  { code: 10, title: "Engenheiro Eletricista" },
  { code: 11, title: "Gerente Administrativo" },
  { code: 12, title: "Técnico de Segurança no Trabalho" },
  { code: 13, title: "Encarregado Administrativo" },
  { code: 14, title: "Encarregado Almoxarifado" },
  { code: 15, title: "Auxiliar de Serviços Gerais" },
  { code: 16, title: "Encarregado de Orçamento" },
  { code: 17, title: "Cadista" },
  { code: 18, title: "Assessor e Consultor" },
  { code: 19, title: "Assessor Jurídico" },
  { code: 21, title: "Assessor de Diretoria" },
  { code: 22, title: "Gerente de Obras" },
  { code: 23, title: "Diretora de Finanças" },
  { code: 24, title: "Diretor Geral" },
  { code: 26, title: "Diretora Gerente" },
  { code: 27, title: "Auxiliar de Engenheiro da Construção Civil" },
  { code: 28, title: "Estagiário" },
  { code: 29, title: "Auxiliar de Transporte" },
  { code: 30, title: "Engenheiro Trainee" },
  { code: 32, title: "Gerente Administrativo RH" },
  { code: 33, title: "Eletricista AT/BT" },
  { code: 34, title: "Assistente Administrativo" },
  { code: 35, title: "Gerente de Operação" },
  { code: 36, title: "Eletricista Industrial/Aprendiz" },
  { code: 37, title: "Assistente Administrativo/Aprendiz" },
  { code: 39, title: "Almoxarife" },
  { code: 42, title: "Assistente Administrativo II" },
  { code: 43, title: "Chefe de Frota" },
  { code: 44, title: "Recepcionista" },
  { code: 45, title: "Podador" },
  { code: 47, title: "Operador de Computador/Aprendiz" },
  { code: 48, title: "Zelador de Edifício" },
  { code: 50, title: "Podador" },
  { code: 51, title: "Motorista/Operador de Caminhão Munck" },
  { code: 52, title: "Engenheiro(a) de Segurança do Trabalho" },
  { code: 54, title: "Fiscal SRD/RE" },
  { code: 55, title: "Coordenador(a) Administrativo" },
  { code: 56, title: "Auxiliar de Almoxarife" },
  { code: 57, title: "Líder de Frota" },
  { code: 58, title: "Assistente de Frota" },
  { code: 59, title: "Coordenador Financeiro" },
  { code: 60, title: "Técnico de Projetos/Cadista" },
  { code: 61, title: "Levantador" },
  { code: 62, title: "Fiscal de Obras" },
  { code: 63, title: "Comprador" },
  { code: 64, title: "Planejador" },
  { code: 65, title: "Coordenador Técnico" },
  { code: 67, title: "Médico do Trabalho" },
  { code: 68, title: "Encarregado" },
  { code: 69, title: "Engenheiro Civil" },
  { code: 71, title: "Eletricista AT/BT Sênior" },
  { code: 72, title: "Assistente Administrativo I" },
  { code: 73, title: "Gerente de Gente e Gestão" },
  { code: 74, title: "Operador de Empilhadeira" },
  { code: 75, title: "Coordenador de Planejamento e Medição" },
  { code: 76, title: "Supervisor de Suprimento e Logística" },
  { code: 77, title: "Coordenador dos Serviços Técnicos e Comerciais" },
  { code: 78, title: "Assistente Administrativo RH I" },
  { code: 79, title: "Técnico(a) em Enfermagem do Trabalho" },
  { code: 80, title: "Supervisor de Frota" },
  { code: 81, title: "Pedreiro" },
  { code: 82, title: "Servente de Obras" },
  { code: 83, title: "Analista Contábil" },
  { code: 84, title: "Pintor" },
  { code: 85, title: "Líder de Almoxarife" },
  { code: 86, title: "Carpinteiro" },
  { code: 87, title: "Inspetor de Frota" },
  { code: 88, title: "Assistente Administrativo RH II" },
  { code: 89, title: "Analista de Encerramento" },
  { code: 90, title: "Planejador de Manutenção" },
  { code: 91, title: "Controller" },
  { code: 92, title: "Técnico de Obras" },
  { code: 93, title: "Coordenador de Frota" },
  { code: 94, title: "Analista de Compras Sênior" },
  { code: 95, title: "Motorista de Carreta/Operador de Munck" },
  { code: 96, title: "Auxiliar de Carga e Descarga" },
  { code: 97, title: "Supervisor de Segurança do Trabalho" },
  { code: 98, title: "Vigilante Orgânico" },
  { code: 99, title: "Auxiliar de Serviços Gerais II" },
  { code: 100, title: "Coordenador de Segurança" },
  { code: 101, title: "Motorista de Caminhão" },
  { code: 102, title: "Analista de Logística" },
  { code: 103, title: "Coordenador de Logística" },
  { code: 104, title: "Analista de Performance" },
  { code: 105, title: "Supervisor de T.I." },
  { code: 106, title: "Analista de Compras Jr" },
  { code: 107, title: "Eletricista Linha Viva" },
  { code: 108, title: "Encarregado Linha Morta" },
  { code: 109, title: "Encarregado Linha Viva" },
  { code: 110, title: "Planejador de Obras" },
  { code: 111, title: "Especialista de Performance" },
  { code: 112, title: "Fiscal de Campo" },
  { code: 113, title: "Levantador de Obras" },
  { code: 114, title: "Auxiliar de RH" },
  { code: 115, title: "Coordenador Tático" },
  { code: 116, title: "Líder de Baixa de OS" },
  { code: 117, title: "Técnico de Medição" },
  { code: 118, title: "Supervisor de Turno" },
  { code: 119, title: "Supervisor de Logística" },
  { code: 120, title: "Programador de Obras" },
  { code: 121, title: "Assistente de T.I." },
  { code: 122, title: "Técnico em Eletrotécnica" },
  { code: 123, title: "Encarregado de Poda" },
  { code: 124, title: "Prospector" },
  { code: 125, title: "Eletricista Predial" },
  { code: 126, title: "Supervisor de Planejamento e Medição" },
  { code: 127, title: "Fiscal de Campo SR" },
  { code: 128, title: "Supervisor de Turno SR" },
  { code: 129, title: "Líder de Medição" },
  { code: 130, title: "Fiscal de Campo Jr" },
  { code: 131, title: "Analista de RH" },
  { code: 132, title: "Assistente Administrativo SR" },
  { code: 133, title: "Líder de Planejamento" },
  { code: 134, title: "Analista de Medição" },
  { code: 135, title: "Encarregado de Frota" },
  {
    code: 136,
    title: "Executiva Corporativa de Estratégia Técnica e Comercial",
  },
  { code: 137, title: "Técnico de Projetos" },
  { code: 138, title: "Técnico de Segurança no Trabalho SR" },
  { code: 139, title: "Técnico de Projetos Pleno" },
  { code: 140, title: "Levantador de Medição Fiscal" },
  { code: 141, title: "Supervisor de Função e Medição" },
  { code: 142, title: "Coordenador de T.I." },
  { code: 143, title: "Coordenador de Compras" },
  { code: 144, title: "Técnico de Medição SR" },
  { code: 145, title: "Engenheiro(a) Florestal" },
  { code: 146, title: "Supervisor Operacional" },
  { code: 147, title: "Analista Sênior Corporativa de Sustentabilidade" },
  { code: 148, title: "Analista de Distribuição SR" },
  { code: 149, title: "Operador de Trator" },
  { code: 150, title: "Operador de Máquinas" },
  { code: 151, title: "Encarregado de Roço" },
  { code: 152, title: "Ajudante de Roço" },
  { code: 153, title: "Operador de Motosserra" },
  { code: 154, title: "Supervisor de Equipe de Roço" },
  { code: 155, title: "Assistente de Comunicação e Marketing" },
  { code: 156, title: "Analista de Dados e Desenvolvimento PL" },
  { code: 157, title: "Analista de RH PL" },
  { code: 158, title: "Oficial de Manutenção Predial" },
  { code: 159, title: "Assistente Administrativo PL" },
  { code: 160, title: "Supervisor de Almoxarifado" },
  { code: 161, title: "Engenheiro(a) Ambiental" },
  { code: 162, title: "Técnico de Segurança no Trabalho PL" },
  { code: 163, title: "Supervisor de Segurança Patrimonial" },
  { code: 164, title: "Leiturista" },
  { code: 165, title: "Cadastrador" },
  { code: 166, title: "Analista de T.I. Jr" },
  { code: 167, title: "Coordenador de Performance" },
  { code: 168, title: "Assistente Técnico Operacional" },
  { code: 169, title: "Coordenador de Facilities" },
  { code: 170, title: "Analista de Performance PL" },
  { code: 171, title: "Assistente de Engenharia" },
  { code: 172, title: "Assistente de RH" },
  { code: 173, title: "Analista de Performance SR" },
  { code: 174, title: "Planejador de Obras Jr" },
  { code: 175, title: "Técnico de Projeto Jr" },
  { code: 176, title: "Técnico de Medição Jr" },
  { code: 177, title: "Analista de Distribuição PL" },
  { code: 178, title: "Analista de Distribuição PL" },
  { code: 179, title: "Analista Administrativo PL" },
  { code: 180, title: "Comprador Jr" },
  { code: 181, title: "Analista Administrativo de Facilities" },
  { code: 182, title: "Supervisor de Facilities" },
  { code: 183, title: "Analista Administrativo Jr" },
  { code: 184, title: "Líder de Facilities" },
  { code: 185, title: "Coordenador de Gestão e Qualidade" },
  { code: 186, title: "Assistente Financeiro" },
  { code: 187, title: "Técnico de Projeto PL" },
  { code: 188, title: "Mecânico II" },
  { code: 189, title: "Analista Contábil SR" },
  { code: 191, title: "Técnico em Meio Ambiente" },
  { code: 192, title: "Analista Financeiro SR" },
  { code: 193, title: "Motorista de Carreta" },
  { code: 194, title: "Agente de Portaria" },
  { code: 195, title: "Comprador Pleno" },
  { code: 196, title: "Analista de Marketing Jr" },
  { code: 197, title: "Analista Financeiro Jr" },
  { code: 198, title: "Consultora de RH PL" },
  { code: 199, title: "Aprendiz Administrativo" },
  { code: 200, title: "Analista de Medição SR" },
  { code: 201, title: "Analista Contábil Pleno" },
  { code: 202, title: "Analista de Faturamento Pleno" },
  { code: 203, title: "Técnico de Obras SR" },
  { code: 204, title: "Técnico de Medição PL" },
] as const;

export type JobTitleEntry = (typeof jobTitleCatalog)[number];

export const jobTitleOptions = Array.from(
  new Set(jobTitleCatalog.map(({ title }) => title)),
).sort((a, b) => a.localeCompare(b, "pt-BR"));
